In [1]:
import vocab
import re

import torch
import torch.nn as nn
import torch.nn.functional as F


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/outbell/Ajay/DeepLearning/GenAI/smallGPT/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/outbell/Ajay/DeepLearning/GenAI/smallGPT/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/outbell/Ajay/DeepLearning/GenAI/smallGPT/.venv/lib/python3.12/site-pack

In [7]:
pos = torch.arange(1, 4, dtype = torch.long).unsqueeze(0).unsqueeze(0).unsqueeze(-1)
c = torch.randn(1, 1, 3, 4)
print(c)
c = c*pos
print(c)

tensor([[[[-0.3748,  0.4437,  1.3399,  0.2248],
          [ 1.0240, -1.5314,  0.5725,  0.9506],
          [-1.3532, -0.9369,  1.2231, -0.3489]]]])
tensor([[[[-0.3748,  0.4437,  1.3399,  0.2248],
          [ 2.0480, -3.0628,  1.1450,  1.9012],
          [-4.0596, -2.8107,  3.6693, -1.0467]]]])


In [12]:
torch.tril(torch.ones((3, 3), dtype = torch.float))

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])

In [7]:
1.00 / attn.float()

tensor([[1.0000, 1.0000, 0.5000],
        [0.5000, 0.2500, 0.5000],
        [0.3333, 0.5000, 0.5000]])

In [12]:
x = ['a', 'b', 'c', 'd', 'e', 'f', 'd']
x_ixs = [0, 1, 2, 3, 4, 5, 6]
for i, k in enumerate(x):
    if k in ['b', 'd']:
        x.pop(i)
        x_ixs.pop(i)
        print(x, x_ixs)
print(x)
print(x_ixs)


['a', 'c', 'd', 'e', 'f', 'd'] [0, 2, 3, 4, 5, 6]
['a', 'c', 'e', 'f', 'd'] [0, 2, 4, 5, 6]
['a', 'c', 'e', 'f'] [0, 2, 4, 5]
['a', 'c', 'e', 'f']
[0, 2, 4, 5]


In [2]:
torch.sigmoid(torch.tensor([0.2, 0.4, 0.9, 0.22]))

tensor([0.5498, 0.5987, 0.7109, 0.5548])

In [7]:
with open('D:\DeepLearning\smallGPT\data\shakesphere.txt', 'r') as f:
    data = f.read()

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\PC\AppData\Local\Temp\ipykernel_6848\3709310658.py:1: SyntaxWarning: invalid escape sequence '\D'
  with open('D:\DeepLearning\smallGPT\data\shakesphere.txt', 'r') as f:


In [9]:
# Split the text data based on multiple delimiters
words = re.split(r'[ ,.\n]+', data)
print(len(set(words)))

19994


In [22]:
t = torch.randint(0, 100, (2, 2, 2))
print(t[0, -1, -1])
if t[0, -1, -1] in torch.tensor([77, 78]):
    print("yes")

tensor(78)
yes


In [2]:
torch.randint(0,0, (1, ))

RuntimeError: random_ expects 'from' to be less than 'to', but got from=0 >= to=0